version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:2.0.0
    command: -H unix:///var/run/docker.sock
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - backplane
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "portainer-data:/data"
    labels:
      - "backplane.enabled=true"
      # - "traefik.http.routers.portainer.entrypoints=http"
      # - "traefik.http.routers.portainer.rule=Host(`portainer.${BACKPLANE_DOMAIN}`)"
      # - "traefik.http.routers.portainer.middlewares=compress@docker"
      - "traefik.http.routers.http-portainer.service=portainer"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"

volumes:
  portainer-data:

networks:
  backplane:
    name: backplane
    external: true