version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:2.0.0
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - backplane
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "portainer-data:/data"
    labels:
      - "backplane.enabled=true"

volumes:
  portainer-data:

networks:
  backplane:
    name: backplane
    external: true