
FROM ubuntu:latest

RUN apt update && apt install --no-install-recommends openssh-server sudo python3-pip -y \
    && pip3 install docker-compose

RUN mkdir -p /runner/repositories /runner/hooks /runner/deployments \
    && chown 1000:1000 /runner -R

RUN useradd -rm -d /runner -s /bin/bash -g root -G sudo -u 1000 git \
    && echo "git:git" | chpasswd

RUN mkdir -p /runner/.ssh/ \
    && touch /runner/.ssh/known_hosts \
    && touch /runner/.ssh/authorized_keys \
    && chown git:root /runner -R

COPY config/ssh_config /etc/ssh/ssh_config
COPY config/sshd_config /etc/ssh/sshd_config
COPY backplane-ssh /usr/local/bin/backplane-ssh
COPY backplane-runner /usr/local/bin/backplane-runner
COPY post-receive /runner/hooks/post-receive
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh

RUN echo 'PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin"' >> /runner/.profile \
    && echo "git ALL=NOPASSWD:/usr/local/bin/backplane*" >> /etc/sudoers

RUN chmod +x /usr/local/bin/backplane-ssh /usr/local/bin/backplane-runner /runner/hooks/post-receive /usr/local/bin/docker-entrypoint.sh
 
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
 
CMD tail -f /dev/null

    